services:
  postgres:
    image: 'postgres:14'
    environment:
      - 'POSTGRES_DB=symplifica_order_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=admin'
    ports:
      - '5432:5432'
